### ISSUE TITLE
Not able to attach button

### ISSUE THREAD

**Issue by cattnips** [JennoVink/MidiKeyboardSoundboard#1]
When clicking on "click to attach button", some red text also flashes for a split second and it automatically assigns what I'm assuming is the key 'pressed' to 00. I'm fairly sure the text says something about recording? I'm using an Arturia Microbrute. The "click to set stop sound button" and "click to configure the volume knob" also exhibit the same behavior.

**Comment by JennoVink** [comment]
Dear camcam, thanks for raising the issue. It seems that the software thinks that you're pressing a button (or key), but apparently didn't. Can you validate that you didn't touched a button during clicking on the attach button?
This afternoon (it's now 11:00 CET) I'll create a new release which includes a "ignore these midi keys" functionality such that these problems can be bypassed.

**Comment by cattnips** [comment]
Yep, I definitely didn't touch a button. Found something interesting though... in another program (https://github.com/hellslinger/SimpleSampler) the note presses are recorded and printed, in both an output text tab and also when picking the note to trigger a sound. It looks like my midi is sending a constant stream of placeholder notes? From what I can tell though, there's no way to change that functionality on my end.
![SimpleSampler_vOkYmBKDlX](https://user-images.githubusercontent.com/16390086/83860322-1ea7e100-a6ed-11ea-963d-796d04442705.png)

**Comment by JennoVink** [comment]
Thanks for detailed screenshot. It seems that MIDI ports have a functionality called autosensing which sends constant stream of the data illustrated in the screenshot. This may be a feature your Arturia Microbrute which you can turn off (I guess). Please see if [this](http://www.soundquest.org/Help/MidiQuest11/studio-autosenseset.htm) can help you further. Nevertheless I think it's still handy to implement the fix I mentioned earlier.

--edit--
Maybe also check this site: https://www.retrokits.com/rk004/settings/#r0_4

**Comment by JennoVink** [comment]
@camcam2015 Is it possible to run the program from Visual Studio in debug mode? The debug information can be found in the console. I have the feeling that the problem is fairly simple to fix and implementing a "ignore these keys list" would create an unnecessary more complex UI.

**Comment by cattnips** [comment]
Done: here's the output immediately after opening the connection with the midi device 

![devenv_xb139qraZ2](https://user-images.githubusercontent.com/16390086/83924659-200bf480-a753-11ea-80c2-834f07d22935.png)

and the output when I clicked to attach (the only change was that recording started)

![devenv_Ki6TUPf4Pd](https://user-images.githubusercontent.com/16390086/83924797-7b3de700-a753-11ea-9265-dfac9478be94.png)

**Comment by JennoVink** [comment]
I commited new code. Can you please try if that fixes the problem?

**Comment by cattnips** [comment]
Yep, it works PERFECTLY now. Great turnaround on this bug, thank you so much!

**Comment by JennoVink** [comment]
That's great news! You're welcome! 😁
