### ISSUE TITLE
How to launch

### ISSUE THREAD

**Issue by KASDmusic** [JennoVink/MidiKeyboardSoundboard#11]
Hello,

Your work seems to be very nice but could you explain how to launch the app on differents OS in the readme ?

thx a lot.

**Comment by JennoVink** [comment]
You mean operating systems? Like windows, Linux, macOs, etc? I tested it on windows, so I can explain that in the Readme if you want... Or you could also become a collaborator and create a pull request :-). 

Kind regards,
Jenno

**Comment by KASDmusic** [comment]
Yes I was meaning operating systems,

I never used an application programmed in CSharp and I'm kind a beginner on github so I definitely can't help you to do it :'(

respectfully,
KASDmusic.

**Comment by KASDmusic** [comment]
(I want to use it on windows)

**Comment by JennoVink** [comment]
I can help you out, don't worry. The easiest way is to download the release. Did you do that?

https://github.com/JennoVink/MidiKeyboardSoundboard/files/4433919/Release.zip

**Comment by JennoVink** [comment]
Tried it yet? I'm looking forward to your reaction :-)
