### ISSUE TITLE
Longer file names cause UI issues

### ISSUE THREAD

**Issue by TelepathicRyuu** [JennoVink/MidiKeyboardSoundboard#19]
Something that I noticed with file names that are longer than one line is that the remove button gets moved so far down you cant actually remove it (This can be fixed by changing the file to a file name that is smaller).

![image](https://user-images.githubusercontent.com/23217454/217392190-596b0030-cc73-4b53-bf98-71b5320e7a3b.png)

**Comment by JennoVink** [comment]
@TelepathicRyuu Please checkout the new release at https://github.com/JennoVink/MidiKeyboardSoundboard/releases/tag/v1.5
Let me know what you think! Please reopen if you have other good ideas.
