### ISSUE TITLE
Volume knob changes volume of all programs, is this expected behavior?

### ISSUE THREAD

**Issue by cattnips** [JennoVink/MidiKeyboardSoundboard#2]
I had assumed configuring the volume knob would only effect the program that it's configured in (MainWindow in the gif) and not the device all audio is being pushed to. Just wanted to know if that's expected behavior!

![75hnUelwl2](https://user-images.githubusercontent.com/16390086/83950592-ef32ca80-a7f9-11ea-9c5e-244f284d533f.gif)

**Comment by JennoVink** [comment]
This was the intended behaviour yes. Maybe in the future this will change (set volume level per sound slot).

**Comment by cattnips** [comment]
Gotcha. What file(s) would I have to look at to try adding something like that? I'd love to make a couple pull requests :)

**Comment by JennoVink** [comment]
Great idea! Here are some important files:
MidiKeyboardSoundboard/MidiKeyboardSoundboard/Model/SoundEntry.cs --> here is the sound played.
Maybe change the method header of the play method to         public void Play(int volumeLevel)
Then: make sure the volume level is reflected in the rest of the application.
MidiKeyboardSoundboard/MidiKeyboardSoundboard/ViewModel/MainViewModel.cs:setVolume(int volume) method is called when rotating the sound knob. I think it's a good idea to introduce a VolumeLevel variable that can be read when playing a sound (        private void PlaySound(string midiKeyIndex) in the MainViewModel).

Hopfully this gave you some ideas to start.

If you have any questions, let me know!

**Comment by JennoVink** [comment]
@camcam2015 any updates? Or can this issue be closed?
