### ISSUE TITLE
[Feature] Play audio on microphone track

### ISSUE THREAD

**Issue by HypedDomi** [JennoVink/MidiKeyboardSoundboard#3]
As the title suggests, I would like to play the audio on my micro so that it can be heard on Discord. I am currently streaming the output to a microtrack with another program. But if the program could do that itself, it would be nice because then you don't need an extra program

**Comment by JennoVink** [comment]
Thanks for opening this issue. Which software are you using right now for streaming the soundboard output to the microphone input? Just curious ;)

**Comment by domi-btnr** [comment]
Currently [VB Cable](https://vb-audio.com/Cable/index.htm)

**Comment by JennoVink** [comment]
Alright. Do you need to configure anything in VB Cable in order to make it work? E.g. is it just a manner of turning in the program? Or is extensive configuration needed.

On first sight, it looks like porting a normal audio-out track, to a microphone-in isn't really easy to do in .NET..

**Comment by domi-btnr** [comment]
It's easy to set up. In the Windows Audio Mixer, simply set the output to VB Cable and also set your microphone to the VB Cable so that others can hear you. Then just set the microphone and you're done.

If it doesn't work with the micro track, that's OK. Then you can use VB Cable. If you want, I can write you a documentary that explains better how to set it up

**Comment by JennoVink** [comment]
Looking at all the configuration options in VB Cable, I think the tool I created'll become too complex if I implement all these features.

It would be great if you edit the Readme.md to add a small manual in order to setup VB Cable in combination with this project.

**Comment by domi-btnr** [comment]
I created a [Pull Request](https://github.com/JennoVink/MidiKeyboardSoundboard/pull/4)

**Comment by JennoVink** [comment]
merged pull request. Thank you for your collaboration.
