### ISSUE TITLE
Doesnt Show up in App Volume control

### ISSUE THREAD

**Issue by ThaBigB** [JennoVink/MidiKeyboardSoundboard#8]
is there any fix for this? i cannot hear anything even when properly linked to a working midicontroller. Also it doesnt show up in App-Volume Control for me to set it into VB-Cable

**Comment by ThaBigB** [comment]
I was able to get it into the App Volume Control now but still cannot hear anything sadly

**Comment by JennoVink** [comment]
Maybe it's a good idea to temporarily set the audio playback device to the normal speaker, and go on from there.  [Screenshot](https://winaero.com/blog/wp-content/uploads/2018/01/Windows-10-Choose-Default-Audio-Device.png).

Can you maybe add a screenshot of the application? I might implement an option where you can export/locate the settings file (would come in handy now).

**Comment by JennoVink** [comment]
No reaction. Please reopen if you have more info.

**Comment by Rhine5t0ne** [comment]
hey I'm currently struggling with this, no matter what, I cant get it to show up.

**Comment by JennoVink** [comment]
@Rhine5t0ne do you have the exact same problems as @ThaBigB ? Is the app itself connected to your midi device? This means that the midi device is listed in a dropdown menu.

Kind regards,
Jenno

**Comment by Rhine5t0ne** [comment]
yes midi device is connected and the interface works, I'm just unable to get audio control.

**Comment by Rhine5t0ne** [comment]
@JennoVink i am able to input keys but am unable to route the app audio via the app volume and device preferences settings.

**Comment by JennoVink** [comment]
@Rhine5t0ne are you also using VB Cable? Or any external software.

**Comment by Rhine5t0ne** [comment]
@JennoVink I have a vb cable installed but am unable to link it because i cannot access the settings for the app.
