### ISSUE TITLE
Sound thru app sound issue?

### ISSUE THREAD

**Issue by Triqunox** [JennoVink/MidiKeyboardSoundboard#9]
I'm a little confused on how this works? 
Iv downloaded it opened the Exe file it opened up automatically knew I had the MPK mini 3
assigned the keys selected the file path to an mp3 like 9 seconds. pushed the button on the pad and nothing comes out?
 is there a second application I need also. note I do not have any of the Akai software installed at the moment maybe that is the issue.
![Keyboard](https://user-images.githubusercontent.com/102944347/161484931-118798c7-9808-4860-8bad-47ae6f496a2e.png)

**Comment by JennoVink** [comment]
Dear @Triqunox,

Thanks for your message, I'm considering implementing a help/tutorial screen. For now: first click the 'select filepath' button. You can select multipe files (then multiple keys are added). For a key, click the button with 'Click to attach button'. The software will wait for a midi input. Press a phisical key on the midi keyboard and you're good to go. Make sure the sound is on :-). 

Let me know how it goes!

**Comment by JennoVink** [comment]
Please reopen if you still have the same problem @Triqunox
